upgrade CostExplorer sdk version to support cost category default value
aws-cloudformation/aws-cloudformation-resource-providers-cost-explorer pull request #11
Opened 2021-04-01 17:13 UTC by hailengc

Upgrade CostExplorer sdk version to support cost category default value

*Description of changes:*

1. upgrade CE sdk version to support  latest cost category API
2. add new property "DefautlValue" in `aws-ce-costcategory.json` 
3. unit test update cover `DefaultValue`
4. fix limitation for cost category "Name" to be maximum 50
5. fix to use explicit `assert` in Groovy closure, otherwise it does not report failure 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-01 18:52 UTC, wangyuhere commented on costcategory/pom.xml
> +            <version>2.16.30</version>
Since we also released inherited value rule type, new models are added for example [CostCategoryInheritedValueDimension](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_CostCategoryInheritedValueDimension.html). We might also need code change [here](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cost-explorer/blob/master/costcategory/src/main/java/software/amazon/ce/costcategory/CostCategoryRulesParser.java) to support it. And you can update [test](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cost-explorer/blob/master/costcategory/src/test/groovy/software/amazon/ce/costcategory/CostCategoryRulesParserTest.groovy) to cover the inherited value rule type use cases.

2021-04-01 19:00 UTC, hailengc commented on costcategory/pom.xml
> +            <version>2.16.30</version>
Thanks I was just looking at that part since I got an integration failure again inherited value.

2021-04-01 19:00 UTC, wangyuhere commented on costcategory/src/test/groovy/software/amazon/ce/costcategory/UpdateHandlerTest.groovy
> +            assert updateRequest.rules() == [ RULE_DIMENSION ]
Do you also need to assert `defaultValue` is set here?

2021-04-01 19:02 UTC, hailengc commented on costcategory/src/test/groovy/software/amazon/ce/costcategory/UpdateHandlerTest.groovy
> +            assert updateRequest.rules() == [ RULE_DIMENSION ]
It should, missed

2021-04-05 16:26 UTC, wangyuhere requested changes

2021-04-05 16:26 UTC, wangyuhere commented on costcategory/src/test/groovy/software/amazon/ce/costcategory/Fixtures.groovy
> +    static final String JSON_RULE_INHERITED_VALUE = '''{
Have you also added this fixture in the [test](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cost-explorer/blob/master/costcategory/src/test/groovy/software/amazon/ce/costcategory/CostCategoryRulesParserTest.groovy)?

2021-04-05 20:43 UTC, hailengc commented on costcategory/src/test/groovy/software/amazon/ce/costcategory/Fixtures.groovy
> +    static final String JSON_RULE_INHERITED_VALUE = '''{
Not yet, will update

2021-04-06 16:54 UTC, wangyuhere approved these changes

2021-04-06 18:46 UTC, mchestr approved these changes

2021-04-06 18:53 UTC, anatolyburtsev approved these changes

2021-04-06 20:26 UTC, merged